config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :images
  resources :departaments
  resources :clients
  resources :buildings
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "departaments#index"
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :departament
  belongs_to :user
  has_many :images, as: :imageable
  

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ edit update destroy new ]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:description, :departament_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :departament_id, style: "display: block" %>
    <%= form.text_field :departament_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div class="card"   >
  <div class="card-body">
    <div id="<%= dom_id publication %>">
      <div class="row">
        <% publication.departament.images.each_with_index do |image, index| %>
          <div class="col-md-4">
            <%= image_tag(image, width: 250, height: 250, class: "img-fluid") %>
          </div>
        <% end %>
      </div>

      <div class="row mt-3">
        <div class="col-md-6">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <th>Descripcipción</th>
                <td><%= publication.description %></td>
              </tr>
              <tr>
                <th>Habitaciones</th>
                <td><%= publication.departament.bedrooms %></td>
              </tr>
              <tr>
                <th>Piso</th>
                <td><%= publication.departament.floor %></td>
              </tr>
              <tr>
                <th>Numero departamento</th>
                <td><%= publication.departament.number %></td>
              </tr>
              <tr>
                <th>Baños</th>
                <td><%= publication.departament.bathrooms %></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="col-md-6">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <th>metros cuadrados</th>
                <td><%= publication.departament.squaremeters %></td>
              </tr>
              <tr>
                <th>Precio</th>
                <td><%= publication.departament.price %></td>
              </tr>
              <tr>
                <th>Cliente</th>
                <td><%= publication.departament.client.name %></td>
              </tr>
              <tr>
                <th>Edificio</th>
                <td><%= publication.departament.building.name %></td>
              </tr>
              <tr>
                <th>Estado</th>
                <td><%= publication.departament.status.name %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publications</h1>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Show this publication", publication, class: "btn btn-dark" %>
    </p>
  <% end %>
</div>

<%= link_to "New publication", new_publication_path, class: "btn btn-dark" %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/show.html.erb
<div class="container-fluid mt-4"> <!-- Utilizamos 'container-fluid' en lugar de 'container' para que ocupe todo el ancho disponible -->
  <div class="row justify-content-center">
    <div class="col-md-8">
      <p style="color: green"><%= notice %></p>
      <%= render @publication %>
    </div>
  </div>

      <h3>Servicios disponibles en el edificio</h3>
      <table class="table">
        <thead>
          <tr>
            <th>Service</th>
          </tr>
        </thead>
        <tbody>
          <% @publication.departament.building.services.each do |service| %>
            <tr>
              <td><%= service.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <%= link_to "Edit this publication", edit_publication_path(@publication), class: "btn btn-primary mr-2" %>
      <%= link_to "Back to publications", publications_path, class: "btn btn-secondary mr-2" %>
      <%= button_to "Destroy this publication", @publication, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>