config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :images
  resources :departaments
  resources :clients
  resources :buildings
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "departaments#index"
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :comuna
  has_and_belongs_to_many :services

  
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show edit update destroy ]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to building_url(@building), notice: "Building was successfully created." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to building_url(@building), notice: "Building was successfully updated." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "Building was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:name, :street, :number, :comuna_id, service_ids: [])
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_building.html.erb
<div id="<%= dom_id building %>">
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Nombre:</th>
        <td><%= building.name %></td>
      </tr>
      <tr>
        <th>Calle:</th>
        <td><%= building.street %></td>
      </tr>
      <tr>
        <th>Numero:</th>
        <td><%= building.number %></td>
      </tr>
      <tr>
        <th>Comuna:</th>
        <td><%= building.comuna_id %></td>
      </tr>
      <tr>
        <th>Servicios:</th>
        <td>
          <ul>
            <% building.services.each do |service| %>
              <li><%= service.name %></li>
            <% end %>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="mt-3">
    <%= link_to "editar el edificio", edit_building_path(building), class: "btn btn-dark mr-2" %>
    <%= link_to "Volver a los edificios", buildings_path, class: "btn btn-dark mr-2" %>
  </div>
</div>

app/views/buildings/_form.html.erb
<%= form_with(model: building) do |form| %>
  <% if building.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
        <% building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :Calle, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :Numeración, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :comuna_id, style: "display: block" %>
    <%= form.collection_select :comuna_id, Comuna.all, :id, :name, prompt: "Selecciona una comuna" %>  </div>
  <div>

  <div class="field">
    <%= form.label 'Selecciona los servicios disponibles' %>
    <% Service.all.each do |service| %>
      <div class="form-check">
        <%= form.check_box :service_ids, { multiple: true }, service.id, nil %>
        <%= form.label service.name, class: 'form-check-label' %>
      </div>
    <% end %>
  </div>




    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "mostrar este edifcio", @building %> |
  <%= link_to "volver a edificios", buildings_path %>
</div>

app/views/buildings/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Edificios</h1>
<%= link_to "Nuevo edificio", new_building_path, class: "btn btn-dark" %>
<div id="buildings">
  <% @buildings.each do |building| %>
    <%= render building %>
    <p>
      <%= link_to "Mostrar el edificio", building, class: "btn btn-dark" %>
    </p>
  <% end %>
</div>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "Back to buildings", buildings_path %>
</div>

app/views/buildings/show.html.erb
<p class="text-success"><%= notice %></p>

<%= render @building %>

<div>
  <%= link_to "Edit this building", edit_building_path(@building), class: "btn btn-dark" %> |
  <%= link_to "Back to buildings", buildings_path, class: "btn btn-dark" %>

  <%= button_to "Destroy this building", @building, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
</div>