config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :images
  resources :departaments
  resources :clients
  resources :buildings
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "departaments#index"
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:photo, :departament_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :departament_id, style: "display: block" %>
    <%= form.text_field :departament_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Photo:</strong>
    <%= image.photo %>
  </p>

  <p>
    <strong>Departament:</strong>
    <%= image.departament_id %>
  </p>

</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
    <p>
      <%= link_to "Show this image", image %>
    </p>
  <% end %>
</div>

<%= link_to "New image", new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>